### ISSUE TITLE
hide default export warning

### ISSUE THREAD

**Issue by pi0** [danielroe/siroc#85]
Currently building library with default export makes this warning:

> Entry module "src/module.ts" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "src/module.ts" to use named exports only.

Which makes sense to use names exports however there are some packages (like nuxt modules) intentionally need default export.

**Comment by NazmusShakib** [comment]
Did anyone find any solutions regarding this warning? please

**Comment by NazmusShakib** [comment]
Could someone please let me know if they found any solutions to this warning?
